//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleClientForms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Line", Namespace="http://schemas.datacontract.org/2004/07/ScheduleServiceApp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ScheduleClientForms.ServiceReference1.LineWithSchedule))]
    public partial class Line : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string routeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string route {
            get {
                return this.routeField;
            }
            set {
                if ((object.ReferenceEquals(this.routeField, value) != true)) {
                    this.routeField = value;
                    this.RaisePropertyChanged("route");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineWithSchedule", Namespace="http://schemas.datacontract.org/2004/07/ScheduleServiceApp")]
    [System.SerializableAttribute()]
    public partial class LineWithSchedule : ScheduleClientForms.ServiceReference1.Line {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScheduleClientForms.ServiceReference1.Stops stopTimesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScheduleClientForms.ServiceReference1.Stops stopTimes {
            get {
                return this.stopTimesField;
            }
            set {
                if ((object.ReferenceEquals(this.stopTimesField, value) != true)) {
                    this.stopTimesField = value;
                    this.RaisePropertyChanged("stopTimes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Stops", Namespace="http://schemas.datacontract.org/2004/07/ScheduleServiceApp", ItemName="Stop", KeyName="Station", ValueName="Time")]
    [System.SerializableAttribute()]
    public class Stops : System.Collections.Generic.Dictionary<ScheduleClientForms.ServiceReference1.Station, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/ScheduleServiceApp")]
    [System.SerializableAttribute()]
    public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StationSchedule", Namespace="http://schemas.datacontract.org/2004/07/ScheduleServiceApp")]
    [System.SerializableAttribute()]
    public partial class StationSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScheduleClientForms.ServiceReference1.Departures departuresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ScheduleClientForms.ServiceReference1.Station stationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScheduleClientForms.ServiceReference1.Departures departures {
            get {
                return this.departuresField;
            }
            set {
                if ((object.ReferenceEquals(this.departuresField, value) != true)) {
                    this.departuresField = value;
                    this.RaisePropertyChanged("departures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScheduleClientForms.ServiceReference1.Station station {
            get {
                return this.stationField;
            }
            set {
                if ((object.ReferenceEquals(this.stationField, value) != true)) {
                    this.stationField = value;
                    this.RaisePropertyChanged("station");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Departures", Namespace="http://schemas.datacontract.org/2004/07/ScheduleServiceApp", ItemName="Departure", KeyName="Time", ValueName="Line")]
    [System.SerializableAttribute()]
    public class Departures : System.Collections.Generic.Dictionary<string, ScheduleClientForms.ServiceReference1.Line> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ScheduleService")]
    public interface ScheduleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleService/GetLines", ReplyAction="http://tempuri.org/ScheduleService/GetLinesResponse")]
        ScheduleClientForms.ServiceReference1.Line[] GetLines();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleService/GetLine", ReplyAction="http://tempuri.org/ScheduleService/GetLineResponse")]
        ScheduleClientForms.ServiceReference1.LineWithSchedule GetLine(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleService/GetStations", ReplyAction="http://tempuri.org/ScheduleService/GetStationsResponse")]
        ScheduleClientForms.ServiceReference1.Station[] GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScheduleService/GetStationSchedule", ReplyAction="http://tempuri.org/ScheduleService/GetStationScheduleResponse")]
        ScheduleClientForms.ServiceReference1.StationSchedule GetStationSchedule(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScheduleServiceChannel : ScheduleClientForms.ServiceReference1.ScheduleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScheduleServiceClient : System.ServiceModel.ClientBase<ScheduleClientForms.ServiceReference1.ScheduleService>, ScheduleClientForms.ServiceReference1.ScheduleService {
        
        public ScheduleServiceClient() {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScheduleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScheduleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScheduleClientForms.ServiceReference1.Line[] GetLines() {
            return base.Channel.GetLines();
        }
        
        public ScheduleClientForms.ServiceReference1.LineWithSchedule GetLine(string id) {
            return base.Channel.GetLine(id);
        }
        
        public ScheduleClientForms.ServiceReference1.Station[] GetStations() {
            return base.Channel.GetStations();
        }
        
        public ScheduleClientForms.ServiceReference1.StationSchedule GetStationSchedule(string id) {
            return base.Channel.GetStationSchedule(id);
        }
    }
}
